-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 17:17:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AulaDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AulaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AulaDB` DEFAULT CHARACTER SET utf8 ;
USE `AulaDB` ;

-- -----------------------------------------------------
-- Table `AulaDB`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AulaDB`.`Menu` (
  `idMenu` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `icone` VARCHAR(100) NOT NULL,
  `exibir` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idMenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AulaDB`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AulaDB`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AulaDB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AulaDB`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Perfil_idx` (`idPerfil` ASC) ,
  CONSTRAINT `fk_Usuario_Perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `AulaDB`.`Perfil` (`idPerfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AulaDB`.`Menu_Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AulaDB`.`Menu_Perfil` (
  `idMenu_Perfil` INT NOT NULL AUTO_INCREMENT,
  `idMenu` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  PRIMARY KEY (`idMenu_Perfil`, `idMenu`, `idPerfil`),
  INDEX `fk_Menu_has_Perfil_Perfil1_idx` (`idPerfil` ASC) ,
  INDEX `fk_Menu_has_Perfil_Menu1_idx` (`idMenu` ASC) ,
  CONSTRAINT `fk_Menu_has_Perfil_Menu1`
    FOREIGN KEY (`idMenu`)
    REFERENCES `AulaDB`.`Menu` (`idMenu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Menu_has_Perfil_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `AulaDB`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
